services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:18
    depends_on:
      - db
    ports:
      - "8069:8069"
    env_file:
      - .env
    environment:
      - ODOO_DB_HOST=${ODOO_DB_HOST}
      - ODOO_DB_PORT=${ODOO_DB_PORT}
      - ODOO_DB_USER=${POSTGRES_USER}
      - ODOO_DB_PASSWORD=${POSTGRES_PASSWORD}
      - ODOO_ADMIN_PASSWD=${ODOO_ADMIN_PASSWD}
    volumes:
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
    command: |
      bash -lc "
      set -e
      cat >/etc/odoo/odoo.conf <<EOF
      [options]
      admin_passwd = ${ODOO_ADMIN_PASSWD}
      db_host = ${ODOO_DB_HOST}
      db_port = ${ODOO_DB_PORT}
      db_user = ${POSTGRES_USER}
      db_password = ${POSTGRES_PASSWORD}
      addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
      list_db = True
      EOF
      exec odoo -c /etc/odoo/odoo.conf
      "
    restart: unless-stopped

volumes:
  db-data:
  odoo-data:
